
server:
  port: 8104

spring:
  application:
    name: springboot2-nacos-config
nacos:
  config:
    server-addr: 127.0.0.1:8848


#    nacos-server-1.0.0.zip
#    unzip nacos-server-1.0.0.zip
#    cd nacos/bin
#    sh startup.sh -m standalone
