spring:
    # \u73AF\u5883 dev|test|prod
    profiles:
        active: dev

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.demo1.mybatisplus.mode
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: AUTO
      #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: not_empty
      #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      column-underline: true
      #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
      #capital-mode: true
      #\u903B\u8F91\u5220\u9664\u914D\u7F6E
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
      #\u81EA\u5B9A\u4E49\u586B\u5145\u7B56\u7565\u63A5\u53E3\u5B9E\u73B0
      #meta-object-handler: com.baomidou.springboot.xxx
      #\u81EA\u5B9A\u4E49SQL\u6CE8\u5165\u5668
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
