spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    max-active: 20
    max-open-prepared-statements: 20
    maxWait: 60000
    min-evictable-idle-time-millis: 300000
    min-idle: 5
    password: 123456
    pool-prepared-statements: false
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    validation-query: SELECT 'x'

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8105
  servlet:
    context-path: /